openapi: 3.0.0
info:
  title: Dokumentasi Admin
  version: v1
servers:
  - url: http://localhost:8080/api/v1
  - url: https://skripsi-245802795341.asia-southeast2.run.app/api/v1
tags:
  - name: admin
    description: admin

paths:
  /register:
    post:
      tags:
        - admin
      summary: Register admin
      description: admin register, setiap field harus terisi, kalo kosong response nya bad request
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - nomor_hp
                - email
                - password
                - confirm_password
              properties:
                username:
                  type: string
                nomor_hp:
                  type: string
                email:
                  type: string
                password:
                  type: string
                confirm_password:
                  type: string
              example:
                username: test
                nomor_hp: 012345678911
                email: testing@test.com
                password: test123
                confirm_password: test123
      responses:
        "201":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: array
                    properties:
                      token:
                        type: string
              example:
                status: true
                message: Register Success
                data: null
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
              examples:
                Empty Field:
                  value:
                    status: false
                    message: <Field> cannot be empty
                    data: null
                Bad Input:
                  value:
                    status: false
                    message: Format data not valid
                    data: null
        "409":
          description: Conflict
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  errorType:
                    type: string
                  data:
                    type: array
              examples:
                Email Exist:
                  value:
                    status: false
                    message: Email already exists
                    data: null
                Username Exist:
                  value:
                    status: false
                    message: Username already exists
                    data: null 