openapi: 3.0.0
info:
  title: Dokumentasi Admin
  version: v1
servers:
  - url: http://localhost:8080/api/v1
  - url: https://skripsi-245802795341.asia-southeast2.run.app/api/v1
tags:
  - name: admin
    description: admin

paths:
  /admin/register:
    post:
      tags:
        - admin
      summary: Register admin
      description: admin register, setiap field harus terisi, kalo kosong response nya bad request
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - email
                - password
                - confirm_password
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
                confirm_password:
                  type: string
              example:
                username: test
                email: testing@test.com
                password: test123
                confirm_password: test123
      responses:
        "201":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: array
                    properties:
                      token:
                        type: string
              example:
                status: true
                message: Register Success
                data: null
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
              examples:
                Empty Field:
                  value:
                    status: false
                    message: <Field> cannot be empty
                    data: null
                Bad Input:
                  value:
                    status: false
                    message: Format data not valid
                    data: null
        "409":
          description: Conflict
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  errorType:
                    type: string
                  data:
                    type: array
              examples:
                Email Exist:
                  value:
                    status: false
                    message: Email already exists
                    data: null
                Username Exist:
                  value:
                    status: false
                    message: Username already exists
                    data: null 
  /admin/laporan-pembelian:
    post:
      tags:
        - admin 
      summary: Ambil jumlah melakukan pembelian kursus.
      description: Endpoint ini mengeprint jumlah user yang melakukan pembelian kurur
      operationId: postLaporanPembelian
      security:
        - bearerAuth: []
      parameters:
        - name: start_date
          in: query
          description: tanggal target awal
          required: true
          schema:
            type: string
          example: 2024-10-01
        - name: end_date
          in: query
          description: tanggal target akhir
          required: true
          schema:
            type: string
          example: 2024-12-01
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        nama:
                          type: string
                        deskripsi:
                          type: string
                        image:
                          type: array
                          items:
                            type: object
                            properties:
                              nama:
                                type: string
                              url:
                                type: string
                              position:
                                type: integer
                        harga:
                          type: integer
                        jadwal:
                          type: array
                          items:
                            type: object
                            properties:
                              hari:
                                type: string
                              jam_mulai:
                                type: string
                              jam_selesai:
                                type: string
                example:
                  status: true
                  message: Get kursus Success
                  data:
                    - id: "86265355-f2a4-4acd-8195-6e56de7aba56"
                      nama: "Corel"
                      deskripsi: "Pelatihan Corel untuk pemula"
                      image:
                        - nama: "Corel"
                          url: "https://test.com/image1.jpg"
                          position: 1
                        - nama: "Corel"
                          url: "https://test2.com/image2.jpg"
                          position: 2
                      harga: 1500000
                      jadwal:
                        - hari: "Senin"
                          jam_mulai: "16:00"
                          jam_selesai: "18:00"
                        - hari: "Selasa"
                          jam_mulai: "16:00"
                          jam_selesai: "18:00"